- name: Ansible copy backend files to remote server
  synchronize:
    src: ~/project/backend
    dest: ~/

- name: print environment variables
  shell: printenv
#  register: printvars
#
#- name: debug environment output
#  debug:
#    var: printvars

- name: Executing node
  shell: |
    cd ~/backend
    pm2 start dist/main.js -f
  register: nodeprocess

- name: debug node output
  debug:
    var: nodeprocess
